### PR TITLE
feat: allow midware start from existing ddb and s3

### PR DESCRIPTION
**Pull request by alvindaiyan**
## Description

For issue #165, the user need to delete and re-create stack from the existing data. 

- added new parameters when stack creation: create_from_exist['yes' or 'no'], exist_bucket['the s3 bucket the user want to reuse or be created']
- when create from exist is yes, no ddb, s3, and sns topic will be recreated, stack will use existing ones (by resource name). if not found, will fail.
- when create from exist is no, it will create all new resources

Test has been down locally:
- create stack from scratch, all works fine
- delete stack and ddb, s3, topics and endpoint related iam roles will stay.
- create again from existing resources works fine:

     - inference use previously created endpoint and models works fine
     - inference result from previous stack works fine    

Fixes # (issue)

issue #165

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### CODE REVIEW

**Review by guming3d — COMMENTED** [review]
So there will be one group of S3/DDB/ECRImages with multiple Api-gateway/lambda connecting to it if we deploy multiple times with "use exist=yes" parameter?
If the original stack been deleted, the following deployed api will all fail. I think adding this mechanism will add a lot of complexity to current middleware, the parameter "use exist" is not clear to let user know how to choose "yes" or "no".

**Comment by alvindaiyan** [comment]
> So there will be one group of S3/DDB/ECRImages with multiple Api-gateway/lambda connecting to it if we deploy multiple times with "use exist=yes" parameter? If the original stack been deleted, the following deployed api will all fail. I think adding this mechanism will add a lot of complexity to current middleware, the parameter "use exist" is not clear to let user know how to choose "yes" or "no".

only one stack will be deployed, no multiple deployment option

**Comment by guming3d** [comment]
> > So there will be one group of S3/DDB/ECRImages with multiple Api-gateway/lambda connecting to it if we deploy multiple times with "use exist=yes" parameter? If the original stack been deleted, the following deployed api will all fail. I think adding this mechanism will add a lot of complexity to current middleware, the parameter "use exist" is not clear to let user know how to choose "yes" or "no".
> 
> only one stack will be deployed, no multiple deployment option

I mean user can deploy multiple times with "use exist=yes" parameter, then we will have multile stacks, right?

**Comment by alvindaiyan** [comment]
> mean user can deploy multiple times with "use exist=yes" pa

should still work

**Review by yike5460 — COMMENTED** [review]
Currently the only key resource we need to retain is DDB for CF update, fixed DDB name will add extra limit for user to deploy multiple CF stack per region, and it's not proper to expose extra parameter to user which can lead to confusion (e.g. user choose yes but input non-existing s3 prefix), also the update process can become limited if we want update other service or DDB primary key/sort key. Maybe we could consider to use custom resource to detect the update stack event and customize our migration logic inside in a more flexible way? For this case, we can detect if DDB with specific prefix exist, if yes, we duplicate all the data then delete the older DDB, or we just create a new DDB if the PK/SK changed, if no, we keep unchanged and let official CF update function do the dirty work, furthermore, we can add all needed migration work into such custom resource without extra parameter exposed to user.

**Review by guming3d — APPROVED** [review]
aproved

**Pull request merged**
