### PR TITLE
fix: Update install.sh to downgrade dreambooth version.

### PR DESCRIPTION
**Pull request by outstandingcandy**
## Description

Update install.sh to downgrade dreambooth version.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by yike5460 — APPROVED** [review]
lgtm

**Review by yike5460 — COMMENTED** [review]
Do we need to modify the pre-flight.sh accordingly?

**Comment by alvindaiyan** [comment]
The bat file needs update as well

**Review by alvindaiyan — APPROVED** [review]
lgtm

**Pull request merged**
