### PR TITLE
feat: Change WebUI EC2 instance

### PR DESCRIPTION
**Pull request by Shellmode**
## Description

The EC2 which deployed Stable Diffusion WebUI does not need so much CPU resources, we won't use that for inference.
r6i.large is a more suitable instance type for WebUI deployment, because the size of model is large and we need more memory than cpu.

Compare the price of r6i.large($0.126/hour in us-east-1) and c5.2xlarge($0.34/hour in us-east-1), we can get about 60% cost saving.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by Shellmode** [comment]
Considering that [switching between SDXL and SD1.5 models might cause memory leaks](https://github.com/awslabs/stable-diffusion-aws-extension/issues/182), 32G memory will be safer.

r6i.xlarge is also recommended.

In a word, the EC2 which deployed Stable Diffusion WebUI is memory intensive, we should us R type instance.

**Comment by alvindaiyan** [comment]
merge to dev, please

**Comment by yike5460** [comment]
The root causing memory leak should be identified first instead of replace with larger memory instance, since model switch issue should not reside in local server anymore to adopt such solution (fake model placeholder will place on the webui and actual switch will happened on the SageMaker)

**Comment by Shellmode** [comment]
It's obvious that R type instance is more suitable than C type, even if the solution don't really need to load the model into memory, because we have many users on the EC2(WebUI) and it's very hard to avoid loading the real model into memory, [switching models between SDXL and SD1.5/2.1 will cause WebUI OOM](https://github.com/awslabs/stable-diffusion-aws-extension/issues/182), then all users won't be able to use the GPU resources on cloud even though the GPU resources are idle.

In my experiment, memory usage goes up caused by switching models stays at 30G or so, replacing the instance type is a quick(maybe temporary) solution to solve the current problem.

**Comment by Shellmode** [comment]
And I'm not clear the reason why use c5.2xlarge

**Pull request closed without merging**
